markdown: kramdown
highlighter: rouge
title: "Chris Luedtke"
subtitle: "Cloud and Data Engineer · Cincinnati"
author: "Chris Luedtke"
collections:
  tags:
    output: true
  portfolio:
defaults:
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "blog"
      title: "Chris Luedtke"
      header_img: "/assets/images/blog-bg.jpg"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      header_img: "/assets/images/home-bg.jpg"